// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/github.com/smancke/guble/server/interfaces.go

package server

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of PubSubSource interface
type MockPubSubSource struct {
	ctrl     *gomock.Controller
	recorder *_MockPubSubSourceRecorder
}

// Recorder for MockPubSubSource (not exported)
type _MockPubSubSourceRecorder struct {
	mock *MockPubSubSource
}

func NewMockPubSubSource(ctrl *gomock.Controller) *MockPubSubSource {
	mock := &MockPubSubSource{ctrl: ctrl}
	mock.recorder = &_MockPubSubSourceRecorder{mock}
	return mock
}

func (_m *MockPubSubSource) EXPECT() *_MockPubSubSourceRecorder {
	return _m.recorder
}

func (_m *MockPubSubSource) Subscribe(r *Route) *Route {
	ret := _m.ctrl.Call(_m, "Subscribe", r)
	ret0, _ := ret[0].(*Route)
	return ret0
}

func (_mr *_MockPubSubSourceRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Subscribe", arg0)
}

func (_m *MockPubSubSource) Unsubscribe(r *Route) {
	_m.ctrl.Call(_m, "Unsubscribe", r)
}

func (_mr *_MockPubSubSourceRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unsubscribe", arg0)
}

// Mock of MessageSink interface
type MockMessageSink struct {
	ctrl     *gomock.Controller
	recorder *_MockMessageSinkRecorder
}

// Recorder for MockMessageSink (not exported)
type _MockMessageSinkRecorder struct {
	mock *MockMessageSink
}

func NewMockMessageSink(ctrl *gomock.Controller) *MockMessageSink {
	mock := &MockMessageSink{ctrl: ctrl}
	mock.recorder = &_MockMessageSinkRecorder{mock}
	return mock
}

func (_m *MockMessageSink) EXPECT() *_MockMessageSinkRecorder {
	return _m.recorder
}

func (_m *MockMessageSink) HandleMessage(message Message) {
	_m.ctrl.Call(_m, "HandleMessage", message)
}

func (_mr *_MockMessageSinkRecorder) HandleMessage(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HandleMessage", arg0)
}

// Mock of WSConn interface
type MockWSConn struct {
	ctrl     *gomock.Controller
	recorder *_MockWSConnRecorder
}

// Recorder for MockWSConn (not exported)
type _MockWSConnRecorder struct {
	mock *MockWSConn
}

func NewMockWSConn(ctrl *gomock.Controller) *MockWSConn {
	mock := &MockWSConn{ctrl: ctrl}
	mock.recorder = &_MockWSConnRecorder{mock}
	return mock
}

func (_m *MockWSConn) EXPECT() *_MockWSConnRecorder {
	return _m.recorder
}

func (_m *MockWSConn) Close() {
	_m.ctrl.Call(_m, "Close")
}

func (_mr *_MockWSConnRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockWSConn) LocationString() string {
	ret := _m.ctrl.Call(_m, "LocationString")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockWSConnRecorder) LocationString() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LocationString")
}

func (_m *MockWSConn) Send(bytes []byte) error {
	ret := _m.ctrl.Call(_m, "Send", bytes)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockWSConnRecorder) Send(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Send", arg0)
}

func (_m *MockWSConn) Receive(bytes *[]byte) error {
	ret := _m.ctrl.Call(_m, "Receive", bytes)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockWSConnRecorder) Receive(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Receive", arg0)
}
