// Automatically generated by MockGen. DO NOT EDIT!
// Source: src/github.com/smancke/guble/server/interfaces.go

package server

import (
	gomock "github.com/golang/mock/gomock"
	guble "github.com/smancke/guble/guble"
	http "net/http"
)

// Mock of PubSubSource interface
type MockPubSubSource struct {
	ctrl     *gomock.Controller
	recorder *_MockPubSubSourceRecorder
}

// Recorder for MockPubSubSource (not exported)
type _MockPubSubSourceRecorder struct {
	mock *MockPubSubSource
}

func NewMockPubSubSource(ctrl *gomock.Controller) *MockPubSubSource {
	mock := &MockPubSubSource{ctrl: ctrl}
	mock.recorder = &_MockPubSubSourceRecorder{mock}
	return mock
}

func (_m *MockPubSubSource) EXPECT() *_MockPubSubSourceRecorder {
	return _m.recorder
}

func (_m *MockPubSubSource) Subscribe(r *Route) *Route {
	ret := _m.ctrl.Call(_m, "Subscribe", r)
	ret0, _ := ret[0].(*Route)
	return ret0
}

func (_mr *_MockPubSubSourceRecorder) Subscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Subscribe", arg0)
}

func (_m *MockPubSubSource) Unsubscribe(r *Route) {
	_m.ctrl.Call(_m, "Unsubscribe", r)
}

func (_mr *_MockPubSubSourceRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unsubscribe", arg0)
}

// Mock of MessageSink interface
type MockMessageSink struct {
	ctrl     *gomock.Controller
	recorder *_MockMessageSinkRecorder
}

// Recorder for MockMessageSink (not exported)
type _MockMessageSinkRecorder struct {
	mock *MockMessageSink
}

func NewMockMessageSink(ctrl *gomock.Controller) *MockMessageSink {
	mock := &MockMessageSink{ctrl: ctrl}
	mock.recorder = &_MockMessageSinkRecorder{mock}
	return mock
}

func (_m *MockMessageSink) EXPECT() *_MockMessageSinkRecorder {
	return _m.recorder
}

func (_m *MockMessageSink) HandleMessage(message *guble.Message) {
	_m.ctrl.Call(_m, "HandleMessage", message)
}

func (_mr *_MockMessageSinkRecorder) HandleMessage(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HandleMessage", arg0)
}

// Mock of WSConn interface
type MockWSConn struct {
	ctrl     *gomock.Controller
	recorder *_MockWSConnRecorder
}

// Recorder for MockWSConn (not exported)
type _MockWSConnRecorder struct {
	mock *MockWSConn
}

func NewMockWSConn(ctrl *gomock.Controller) *MockWSConn {
	mock := &MockWSConn{ctrl: ctrl}
	mock.recorder = &_MockWSConnRecorder{mock}
	return mock
}

func (_m *MockWSConn) EXPECT() *_MockWSConnRecorder {
	return _m.recorder
}

func (_m *MockWSConn) Close() {
	_m.ctrl.Call(_m, "Close")
}

func (_mr *_MockWSConnRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockWSConn) Send(bytes []byte) error {
	ret := _m.ctrl.Call(_m, "Send", bytes)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockWSConnRecorder) Send(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Send", arg0)
}

func (_m *MockWSConn) Receive(bytes *[]byte) error {
	ret := _m.ctrl.Call(_m, "Receive", bytes)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockWSConnRecorder) Receive(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Receive", arg0)
}

// Mock of Startable interface
type MockStartable struct {
	ctrl     *gomock.Controller
	recorder *_MockStartableRecorder
}

// Recorder for MockStartable (not exported)
type _MockStartableRecorder struct {
	mock *MockStartable
}

func NewMockStartable(ctrl *gomock.Controller) *MockStartable {
	mock := &MockStartable{ctrl: ctrl}
	mock.recorder = &_MockStartableRecorder{mock}
	return mock
}

func (_m *MockStartable) EXPECT() *_MockStartableRecorder {
	return _m.recorder
}

func (_m *MockStartable) Start() {
	_m.ctrl.Call(_m, "Start")
}

func (_mr *_MockStartableRecorder) Start() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Start")
}

// Mock of Stopable interface
type MockStopable struct {
	ctrl     *gomock.Controller
	recorder *_MockStopableRecorder
}

// Recorder for MockStopable (not exported)
type _MockStopableRecorder struct {
	mock *MockStopable
}

func NewMockStopable(ctrl *gomock.Controller) *MockStopable {
	mock := &MockStopable{ctrl: ctrl}
	mock.recorder = &_MockStopableRecorder{mock}
	return mock
}

func (_m *MockStopable) EXPECT() *_MockStopableRecorder {
	return _m.recorder
}

func (_m *MockStopable) Stop() {
	_m.ctrl.Call(_m, "Stop")
}

func (_mr *_MockStopableRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stop")
}

// Mock of SetRouter interface
type MockSetRouter struct {
	ctrl     *gomock.Controller
	recorder *_MockSetRouterRecorder
}

// Recorder for MockSetRouter (not exported)
type _MockSetRouterRecorder struct {
	mock *MockSetRouter
}

func NewMockSetRouter(ctrl *gomock.Controller) *MockSetRouter {
	mock := &MockSetRouter{ctrl: ctrl}
	mock.recorder = &_MockSetRouterRecorder{mock}
	return mock
}

func (_m *MockSetRouter) EXPECT() *_MockSetRouterRecorder {
	return _m.recorder
}

func (_m *MockSetRouter) SetRouter(router PubSubSource) {
	_m.ctrl.Call(_m, "SetRouter", router)
}

func (_mr *_MockSetRouterRecorder) SetRouter(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetRouter", arg0)
}

// Mock of SetMessageEntry interface
type MockSetMessageEntry struct {
	ctrl     *gomock.Controller
	recorder *_MockSetMessageEntryRecorder
}

// Recorder for MockSetMessageEntry (not exported)
type _MockSetMessageEntryRecorder struct {
	mock *MockSetMessageEntry
}

func NewMockSetMessageEntry(ctrl *gomock.Controller) *MockSetMessageEntry {
	mock := &MockSetMessageEntry{ctrl: ctrl}
	mock.recorder = &_MockSetMessageEntryRecorder{mock}
	return mock
}

func (_m *MockSetMessageEntry) EXPECT() *_MockSetMessageEntryRecorder {
	return _m.recorder
}

func (_m *MockSetMessageEntry) SetMessageEntry(messageSink MessageSink) {
	_m.ctrl.Call(_m, "SetMessageEntry", messageSink)
}

func (_mr *_MockSetMessageEntryRecorder) SetMessageEntry(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetMessageEntry", arg0)
}

// Mock of Endpoint interface
type MockEndpoint struct {
	ctrl     *gomock.Controller
	recorder *_MockEndpointRecorder
}

// Recorder for MockEndpoint (not exported)
type _MockEndpointRecorder struct {
	mock *MockEndpoint
}

func NewMockEndpoint(ctrl *gomock.Controller) *MockEndpoint {
	mock := &MockEndpoint{ctrl: ctrl}
	mock.recorder = &_MockEndpointRecorder{mock}
	return mock
}

func (_m *MockEndpoint) EXPECT() *_MockEndpointRecorder {
	return _m.recorder
}

func (_m *MockEndpoint) GetHandler() func(http.ResponseWriter, *http.Request) {
	ret := _m.ctrl.Call(_m, "GetHandler")
	ret0, _ := ret[0].(func(http.ResponseWriter, *http.Request))
	return ret0
}

func (_mr *_MockEndpointRecorder) GetHandler() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHandler")
}
