// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/docker/distribution/health (interfaces: Checker)

package router

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Checker interface
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *_MockCheckerRecorder
}

// Recorder for MockChecker (not exported)
type _MockCheckerRecorder struct {
	mock *MockChecker
}

func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &_MockCheckerRecorder{mock}
	return mock
}

func (_m *MockChecker) EXPECT() *_MockCheckerRecorder {
	return _m.recorder
}

func (_m *MockChecker) Check() error {
	ret := _m.ctrl.Call(_m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCheckerRecorder) Check() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Check")
}
